version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: express_com
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/express_com
      JWT_SECRET: devsecret
      STRIPE_KEY: sk_test_123
      STRIPE_WEBHOOK_SECRET: whsec_test
      WEB_BASE_URL: http://localhost:3000
    ports:
      - '4000:4000'
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:4000
    ports:
      - '3000:3000'
    depends_on:
      - api
volumes:
  db_data:
