[build]
  base = "."
  publish = "public"
  command = "echo Build step not required"

[functions]
  directory = "netlify/functions"
  included_files = [
    "views/**",
    "public/**",
    "app.js"
  ]

# Render all app routes via the function so EJS can render
[[redirects]]
  from = "/book"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/bookings"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/success"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/server"
  status = 200
