name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Backend tests
        run: npm -w @express-com/api run test
      - name: Frontend tests
        run: npm -w @express-com/web run test -- --run
      - name: Build
        run: |
          npm -w @express-com/api run build
          npm -w @express-com/web run build
